import { createSchema } from "@ponder/core"

export default createSchema((p) => ({
  Grant: p.createTable(
    {
      id: p.string(),
      recipient: p.string(),
      flowId: p.string(),
      submitter: p.string(),
      parentContract: p.string(),
      isTopLevel: p.boolean(),
      isFlow: p.boolean(),
      title: p.string(),
      description: p.string(),
      image: p.string(),
      tagline: p.string().optional(),
      url: p.string().optional(),
      isRemoved: p.boolean(),
      isActive: p.boolean(),
      votesCount: p.string(),
      monthlyIncomingFlowRate: p.string(),
      monthlyOutgoingFlowRate: p.string(),
      monthlyRewardPoolFlowRate: p.string(),
      monthlyBaselinePoolFlowRate: p.string(),
      monthlyBonusPoolFlowRate: p.string(),
      bonusMemberUnits: p.string(),
      baselineMemberUnits: p.string(),
      totalEarned: p.string(),
      tcr: p.string(),
      erc20: p.string(),
      arbitrator: p.string(),
      tokenEmitter: p.string(),
      status: p.int(),
      challengePeriodEndsAt: p.int(),
      isDisputed: p.boolean(),
      isResolved: p.boolean(),
      evidenceGroupID: p.string(),
      createdAt: p.int(),
      baselinePool: p.string(),
      bonusPool: p.string(),
      managerRewardPool: p.string(),
      managerRewardSuperfluidPool: p.string(),
      superToken: p.string(),
      updatedAt: p.int(),
      managerRewardPoolFlowRatePercent: p.int(),
      baselinePoolFlowRatePercent: p.int(),
    },
    {
      isTopLevelIndex: p.index("isTopLevel"),
      isFlowIndex: p.index("isFlow"),
      isRemovedIndex: p.index("isRemoved"),
      updatedAtIndex: p.index("updatedAt"),
      flowIdIndex: p.index("flowId"),
      isDisputedIndex: p.index("isDisputed"),
      isActiveIndex: p.index("isActive"),
    }
  ),
  Vote: p.createTable(
    {
      id: p.string(),
      contract: p.string(),
      recipientId: p.string(),
      tokenId: p.string(),
      bps: p.int(),
      voter: p.string(),
      blockNumber: p.string(),
      isStale: p.boolean(),
      votesCount: p.string(),
    },
    {
      voterIndex: p.index("voter"),
      contractIndex: p.index("contract"),
      recipientIdIndex: p.index("recipientId"),
      isStaleIndex: p.index("isStale"),
    }
  ),
  Dispute: p.createTable(
    {
      id: p.string(),
      disputeId: p.string(),
      arbitrator: p.string(),
      arbitrable: p.string(),
      grantId: p.string(),
      challenger: p.string(),
      votingStartTime: p.int(),
      votingEndTime: p.int(),
      revealPeriodEndTime: p.int(),
      creationBlock: p.int(),
      arbitrationCost: p.string(),
      votes: p.string(),
      // assumes 2 potential choices / parties to vote on
      requesterPartyVotes: p.string(),
      challengerPartyVotes: p.string(),
      ruling: p.int(),
      totalSupply: p.string(),
      isExecuted: p.boolean(),
      evidenceGroupID: p.string(),
    },
    {
      arbitratorIndex: p.index("arbitrator"),
      disputeIdIndex: p.index("disputeId"),
      grantIdIndex: p.index("grantId"),
      evidenceGroupIDIndex: p.index("evidenceGroupID"),
    }
  ),
  DisputeVote: p.createTable(
    {
      id: p.string(),
      arbitrator: p.string(),
      disputeId: p.string(),
      commitHash: p.string(),
      committedAt: p.int(),
      voter: p.string(),
      revealedBy: p.string().optional(),
      revealedAt: p.int().optional(),
      choice: p.int().optional(),
      votes: p.string().optional(),
      reason: p.string().optional(),
    },
    {
      disputeIdIndex: p.index("disputeId"),
      arbitratorIndex: p.index("arbitrator"),
    }
  ),
  TokenHolder: p.createTable(
    {
      id: p.string(),
      tokenContract: p.string(),
      holder: p.string(),
      firstPurchase: p.int(),
      amount: p.string(),
    },
    {
      tokenContractIndex: p.index("tokenContract"),
      holderIndex: p.index("holder"),
    }
  ),
  Evidence: p.createTable(
    {
      id: p.string(),
      arbitrator: p.string(),
      evidenceGroupID: p.string(),
      evidence: p.string(),
      party: p.string(),
      blockNumber: p.string(),
    },
    {
      arbitratorIndex: p.index("arbitrator"),
      evidenceGroupIDIndex: p.index("evidenceGroupID"),
    }
  ),
}))
